### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by SamikshaSankar** [FirmanKurniawan/HTML-Projects#123]
Please assign me this issue

**Comment by SamikshaSankar** [comment]
Why closed?

**Comment by FirmanKurniawan** [comment]
not issue

**Comment by SamikshaSankar** [comment]
What? Can you tell me why u closed this issue?

**Comment by FirmanKurniawan** [comment]
because there is no problem

**Comment by SamikshaSankar** [comment]
> because there is no problem

Yes I know...That's y I am asking to you..can you assign me

**Comment by FirmanKurniawan** [comment]
ok

**Comment by SamikshaSankar** [comment]
?
