### ISSUE TITLE
Acc napa pull aing?

### ISSUE THREAD

**Issue by anonsecteaminc** [FirmanKurniawan/HTML-Projects#17]
Hai bang acc dong :")

**Comment by FirmanKurniawan** [comment]
sudah bang, kalo belum kabarin aja

**Comment by anonsecteaminc** [comment]
Mana bang belum lu acc gak muncul tuh

**Comment by FirmanKurniawan** [comment]
gada request an

**Comment by FirmanKurniawan** [comment]
![image](https://user-images.githubusercontent.com/24487561/136120454-804f2915-3a4c-4d06-856d-f1904d00952b.png)
